language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t dragan1527/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dragan1527/docker-react npm run test -- --coverage